// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1kBdQb3lEBL0jdeQjMv2MKxQ8JtLLKc',
    appId: '1:1048625376516:web:fb5776e37ef76380277451',
    messagingSenderId: '1048625376516',
    projectId: 'ewatchlist11',
    authDomain: 'ewatchlist11.firebaseapp.com',
    storageBucket: 'ewatchlist11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQK6tOfaKtoRGRtNV7_-8_1ecr91aPQBM',
    appId: '1:1048625376516:android:074e97ef60bd29b8277451',
    messagingSenderId: '1048625376516',
    projectId: 'ewatchlist11',
    storageBucket: 'ewatchlist11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqU3sMxll1PxHN_vDp8H4sGAWHtuUibdw',
    appId: '1:1048625376516:ios:2e761fb1178f3fd3277451',
    messagingSenderId: '1048625376516',
    projectId: 'ewatchlist11',
    storageBucket: 'ewatchlist11.appspot.com',
    iosClientId: '1048625376516-11otlbrgluka041fllg99cn3k512ls3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewatchlist',
  );
}
